### ISSUE TITLE
Project Peer Review

### ISSUE THREAD

**Issue by SebasRSoler** [Oliver-886/project-repository#3]
i. Technical issues/bugs

1. Format icons/pictures to the same size and centered inside the table. Other pictures have to be adjusted in height and width.
2. When navigating to the contact page, the top navigation bar moves to the right and becomes off-centered. 

ii. Suggestions on Content

1. Customer feedback page formatting and content could be improved. Especially the reset and submit buttons and spacing between lines. 
2. Marketing and Promotion and Driving Traffic pages still need work and include content. 

Overall, great work!

**Comment by Oliver-886** [comment]
I have formatted icons and pictures to the same size and adjusted the height and width. 
Fixed the navigation of contact page. For contact page I want to keep the button without borders  and I have added content to marketing and promotion and driving traffic. Thanks!
