### ISSUE TITLE
Project Peer Review by James Zhang

### ISSUE THREAD

**Issue by Santiagoooooo** [Oliver-886/project-repository#4]
Hi,
Love your website and great job!
Technical issues/bugs:
1. "Reset" button on the Contact page doesn't clear the comment. 
2.  In the Contact page, the search icon doesn't work. 
Suggestion:
1. Little bit more space in the form on the Contact page will seem better. 
2. Adjust the size of pics(especially the second one ) on the Web design page.

Thanks,
James

**Comment by Oliver-886** [comment]
Hey James, I'm not sure how to reset the comment box. Do you have any suggestions? 
I have fixed everything else
