### ISSUE TITLE
Project Peer Review by Elina Hsueh

### ISSUE THREAD

**Issue by ehsueh2** [Oliver-886/project-repository#5]
**Technical:**

1. Search icon (Magnifying glass) should be same in div as `nav`, not the body. This allows it to stay to the right of "Sitemap" and to be responsive with the rest of the menu.

2. The Search icon on the "Contact Us" page is undefined because it is linked as `<img src="search.png"...` instead of `<img src="images/search.png"...`

**Content:**
1. The "Submit" and "Reset" button on the "Contact Us" page should have clearly defined borders.

2. The Shopify logo and "Home" link on the "Sitemap" page redirect to the same thing. Maybe remove the `<br>` on the page?

**Comment by Oliver-886** [comment]
I have fixed the div and the image src. I have decided to keep the "submit" button without borders. Thank you for feedback!
